Sitegeist:
  Stampede:
    enableCache: true
    publicCacheLifetime: 86400
    collections: []

  # Silhuettes are deprecated the core presets should be used
  # instead. This will be removed in a future release
  Silhouettes:
    properties:
      stampede:
        icon:
          type: string
          defaultValue: ''
          ui:
            reloadIfChanged: true
            label: 'Icon'
            inspector:
              group: icon
              editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                dataSourceIdentifier: 'sitegeist-stampede-icons'

Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Stampede: true
    nodeTypes:
      presets:
        properties:
          stampede:
            icon:
              type: string
              defaultValue: ''
              ui:
                label: 'Icon'
                inspector:
                  editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
                  editorOptions:
                    dataSourceIdentifier: 'sitegeist-stampede-icons'
  Fusion:
    defaultContext:
      Stampede: Sitegeist\Stampede\Eel\IconHelper
  Flow:
    mvc:
      routes:
        'Sitegeist.Stampede':
          position: 'before Neos.Neos'
